[alembic]
script_location = alembic
sqlalchemy.url = postgresql://postgres:password@localhost:5432/tinnicare

[loggers]
keys = root,sqlalchemy,alembic

[logger_root]
level = WARN
handlers =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handlers]
keys =

[formatters]
keys =
